development:
  adapter: redis
  url: redis://192.168.1.235:6379/1
  channel_prefix: Rails_Redis_dev

test:
  adapter: redis
  url: redis://192.168.1.235:6379/1
  channel_prefix: Rails_Redis_test

production:
  adapter: redis
  url: redis://192.168.1.235:6379/1
  channel_prefix: Rails_Redis_production
