development:
  adapter: redis
  url: redis://172.17.0.1:6379/1
  channel_prefix: Rails_Redis_dev

test:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: Rails_Redis_test

production:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: Rails_Redis_production
